apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-pipeline
spec:
  annotations:
    seldon.io/headless-svc: "true"
  name: seldon-pipeline
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - env:
                - name: MODEL_NAME
                  value: src.Preprocessor
                - name: TRACING
                  value: '1'
                - name: JAEGER_AGENT_HOST
                  value: simplest-agent.jaeger.svc
                - name: JAEGER_AGENT_PORT
                  value: '5775'
                - name: JAEGER_SAMPLER_TYPE
                  value: const
                - name: JAEGER_SAMPLER_PARAM
                  value: '1'
                image: dvoitekh/seldon_feast:workshop13
                imagePullPolicy: Always
                name: preprocessor
                resources:
                  requests:
                    memory: '500Mi'
                    cpu: '500m'
                  limits:
                    memory: '1000Mi'
                    cpu: '1000m'
              - env:
                - name: MODEL_NAME
                  value: src.Regressor
                - name: TRACING
                  value: '1'
                - name: JAEGER_AGENT_HOST
                  value: simplest-agent.jaeger.svc
                - name: JAEGER_AGENT_PORT
                  value: '5775'
                - name: JAEGER_SAMPLER_TYPE
                  value: const
                - name: JAEGER_SAMPLER_PARAM
                  value: '1'
                image: dvoitekh/seldon_feast:workshop13
                imagePullPolicy: Always
                name: regressor
                resources:
                  requests:
                    memory: '500Mi'
                    cpu: '500m'
                  limits:
                    memory: '1000Mi'
                    cpu: '1000m'
            terminationGracePeriodSeconds: 1
      graph:
        name: preprocessor
        type: MODEL
        children:
        - name: regressor
          type: MODEL
          children: []
      name: model
      replicas: 1
      labels:
        version: v1
